title: Cristian Assaiante
author: Cristian Assaiante
job_title: Post-Doctoral Researcher at DIAG
affiliation:
  name: Sapienza University of Rome
  legal_name: Sapienza University of Rome
  url: "https://www.uniroma1.it/"
social:
  email: "mailto:assaiante@diag.uniroma1.it"
  github: "https://github.com/cristianassaiante"
  scholar: "https://scholar.google.it/citations?user=Hjz3sBoAAAAJ&hl=it&oi=ao"
  linkedin: "https://www.linkedin.com/in/cristian-assaiante-233032174/"
description: Academic personal website of Cristian Assaiante.
url: "https://cristianassaiante.github.io"
markdown: kramdown
permalink: pretty
layouts_dir: layouts
includes_dir: includes
collections_dir: content
collections:
  publications:
    output: false
  projects:
    output: false